# Generated by Django 5.1.7 on 2025-04-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_views', '0002_rename_is_admin_user_is_staff_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='unamed user', max_length=100),
            preserve_default=False,
        ),
    ]
