# Generated by Django 6.0.3 on 2026-03-09 18:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_views', '0007_mpesa_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('mpesa_paybill', 'M-Pesa Paybill'), ('mpesa_till', 'M-Pesa Till (Buy Goods)'), ('mpesa_send_money', 'M-Pesa Send Money (Personal)'), ('mpesa_pochi', 'M-Pesa Pochi La Biashara'), ('bank_transfer', 'Bank Transfer')], max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('mpesa_number', models.CharField(blank=True, help_text='Phone number for Send Money / Pochi, or Paybill/Till number.', max_length=20)),
                ('mpesa_account_number', models.CharField(blank=True, help_text='Account number (for Paybill only).', max_length=64)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_name', models.CharField(blank=True, max_length=255)),
                ('bank_account_number', models.CharField(blank=True, max_length=64)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('display_name', models.CharField(blank=True, help_text="Friendly label shown to tenants, e.g. 'Landlord M-Pesa'.", max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
