# Generated by Django 6.0.2 on 2026-03-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_views', '0010_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('active', 'Active'), ('expiring', 'Expiring'), ('expired', 'Expired'), ('terminated', 'Terminated')], db_index=True, default='draft', max_length=24),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('filled', 'Filled')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='urgency',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('maintenance', 'Under maintenance')], db_index=True, default='vacant', max_length=20),
        ),
    ]
