# Generated by Django 6.0.2 on 2026-03-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_views', '0012_add_critical_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
