# Generated by Django 6.0.2 on 2026-03-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_views', '0013_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='decline_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='landlord_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional terms or notes for this lease.'),
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
