# Generated by Django 6.0.3 on 2026-04-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_views', '0014_lease_decline_reason_lease_declined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='expected_move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
