# Generated by Django 6.0.3 on 2026-04-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_views', '0015_application_expected_move_in_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(default=dict),
        ),
    ]
